#** ***************************************************************************
# \copyright       EswPla FreeRTOS Project
# \file            m_env_settings.mak
# \brief           Environment Settings for Windows MinGW GCC build
# \Make            GNU Make
#******************************************************************************

#------------------------------------------------------------------------------
# SHELL to execute the commands
#------------------------------------------------------------------------------
SHELL := /bin/bash

#------------------------------------------------------------------------------
# Build root and temporary directories for Windows
#------------------------------------------------------------------------------
BUILDROOT    ?= C:/build_tool
export BUILDROOT

#------------------------------------------------------------------------------
# Temp directory to store temporary files generated by compilers
#------------------------------------------------------------------------------
export S_DIR_TMP_BUILD     ?= C:/temp/build

#------------------------------------------------------------------------------
# Temp directory to store deliverables
#------------------------------------------------------------------------------
export S_DIR_TMP_DELIVERY  ?= $(S_DIR_TMP_BUILD)/delivery

#------------------------------------------------------------------------------
# Temp directory to store makefile logfiles
#------------------------------------------------------------------------------
export S_DIR_TMP_SUPPORT   ?= $(S_DIR_TMP_BUILD)/support

#------------------------------------------------------------------------------
# Verbose/Silent mode macros
#------------------------------------------------------------------------------
AM_V_MAKE                    = $(am_V_MAKE_$(V))
am_V_MAKE_0                  = @echo   MAKE    $(subst /,_,$@)
am_V_MAKE_1                  =

AM_V_CC                      = $(am_V_CC_$(V))
am_V_CC_0                    = @echo   CC      $@
am_V_CC_1                    =

AM_V_GEN                     = $(am_V_GEN_$(V))
am_V_GEN_0                   = @echo   GEN     $(notdir $@)
am_V_GEN_1                   =

AM_V_LIB                     = $(am_V_LIB_$(V))
am_V_LIB_0                   = @echo   LIB     $@
am_V_LIB_1                   =
